# Generated by Django 4.2.1 on 2023-05-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
