# Generated by Django 4.2.1 on 2023-05-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_task_log_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='task',
        ),
        migrations.AddField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('NOT COMPLETED', 'Not Completed'), ('COMPLETED', 'Completed')], default='NOT COMPLETED', max_length=20),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
