# Generated by Django 4.2.1 on 2023-05-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_remove_log_task_log_status_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
