# Generated by Django 4.2.1 on 2023-05-30 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_log_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='created',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
